//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class adquisiciones
    {
        public string Metodo_de_adquisicion { get; set; }
        public Nullable<System.DateTime> Fecha_de_adquisicion { get; set; }
        public string Fuente_de_adquisicion { get; set; }
        public string Numero_de_inventario { get; set; }
        public string Procedencia { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
