//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class descripcion_basica
    {
        public string Numero_de_inventario { get; set; }
        public string Tipo_de_objeto { get; set; }
        public string Nombre_o_tema { get; set; }
        public string Autor { get; set; }
        public string Editor { get; set; }
        public string Taller_imprenta { get; set; }
        public string Marca { get; set; }
        public string Denominacion { get; set; }
        public string Epoca { get; set; }
        public string Cultura { get; set; }
        public string Fecha_pieza { get; set; }
        public string Origen { get; set; }
        public string Tema { get; set; }
        public string Forma { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Conservacion { get; set; }
        public string Inscripciones { get; set; }
        public string Acervo { get; set; }
        public Nullable<int> Avaluo { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
