//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class medidas
    {
        public Nullable<float> Alto { get; set; }
        public Nullable<float> Largo { get; set; }
        public Nullable<float> Ancho { get; set; }
        public Nullable<float> Diametro { get; set; }
        public Nullable<float> Peso { get; set; }
        public string Numero_de_inventario { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
