//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_pieza
    {
        public string NI { get; set; }
        public string NA { get; set; }
        public int id { get; set; }
        public string Numero_de_inventario { get; set; }
        public string Numero_de_autorizacion { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
