//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class piezas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public piezas()
        {
            this.imagenes = new HashSet<imagenes>();
            this.modificaciones = new HashSet<modificaciones>();
            this.movimiento_pieza = new HashSet<movimiento_pieza>();
            this.piezas_verificaciones = new HashSet<piezas_verificaciones>();
            this.ubicaciones = new HashSet<ubicaciones>();
        }
    
        public string Numero_de_inventario { get; set; }
        public int Clave_de_museo { get; set; }
        public string Folio_real { get; set; }
        public string Numero_de_registro { get; set; }
        public string Numero_de_catalogo { get; set; }
        public string Otro_numero { get; set; }
        public Nullable<byte> Control_interno { get; set; }
        public Nullable<int> Cantidad_ampara { get; set; }
        public Nullable<int> NI { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<byte> flag { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string id_ubicacion { get; set; }
        public Nullable<byte> Verificacion_por_centro_de_trabajo { get; set; }
    
        public virtual adquisiciones adquisiciones { get; set; }
        public virtual bajas bajas { get; set; }
        public virtual composicion composicion { get; set; }
        public virtual descripcion_basica descripcion_basica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagenes> imagenes { get; set; }
        public virtual medidas medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modificaciones> modificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_pieza> movimiento_pieza { get; set; }
        public virtual museos museos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<piezas_verificaciones> piezas_verificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicaciones> ubicaciones { get; set; }
    }
}
