//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class piezas_verificaciones
    {
        public int idpiezas_verificaciones { get; set; }
        public string Numero_de_inventario { get; set; }
        public string Id_verificacion { get; set; }
        public Nullable<int> Id_persona { get; set; }
        public Nullable<System.DateTime> Fecha_verificacion { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
