//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicaciones
    {
        public int Id_ubicacion { get; set; }
        public string Ubicacion_Actual { get; set; }
        public Nullable<System.DateTime> Fecha_de_ubicacion { get; set; }
        public string Tipo_de_ubicacion { get; set; }
        public string Ubicacion_normal { get; set; }
        public string Numero_de_inventario { get; set; }
    
        public virtual piezas piezas { get; set; }
    }
}
